verde/__init__.py, verde/tests/test_utils.py, verde/utils.py
Copied over from fatiando.gridder. Uses numpy.random.RandomState.uniform
to generate coordinates for points on a 2D plane. Implements a utility
function `check_region` to make sure the common region argument is
correctly specified.
Fixes #1
=> Add function to generate a scatter of points

environment.yml, requirements.txt, verde/utils.py
Use the `sklearn.utils.check_random_state` instead of coding this up
here. Rename `random_seed` to `random_state` to match.
=> Use scikit-learn utils to handle random state

verde/__init__.py, verde/tests/test_utils.py, verde/utils.py
Function `profile_coordinates` generates coordinates for a profile
between two points.
=> Add function to make coordinates for a profile

data/README.md, data/tiny-data.txt
Smallest file possible just used to test if the data downloading
function works.
=> Create a tiny data file to test downloading

.travis.yml, environment.yml, requirements.txt, verde/datasets/download.py, verde/tests/test_datasets.py, verde/utils.py
Adds function `fetch_data` to get the path of a data file from the data 
directory (`$HOME/.verde/data`). If the file is not present, download it
from Github. 
Uses the requests library to download. In the future, this will allow us
to implement chunked downloads of larger files.
=> Functions to download sample data 

environment.yml, examples/baja_bathymetry.py, examples/checkerboard.py, requirements.txt, verde/datasets/__init__.py, verde/datasets/sample_data.py, verde/tests/test_datasets.py
Adds function `verde.datasets.fetch_baja_bathymetry` that loads the data
into a `pandas.DataFrame`. Include a gallery example for the data using
cartopy to plot with projections.
Fixes #20
=> Function to fetch sample bathymetry data

examples/block_reduce.py, verde/__init__.py, verde/scipy_bridge.py, verde/tests/test_utils.py, verde/utils.py
Function `block_reduce` applies a reduction operation to data in blocks.
Also adds functions `get_region` to get the region from coordinates, 
`block_region` to generate the block boundaries (a generator), and
`inside` to get check which points are inside a given region. `inside`
allows passing in output and temporary arrays to avoid the overhead of
allocation in `block_reduce`.
Fixes #24
=> Add function to reduce data in blocks

README.rst, doc/index.rst
Set these in the docs and README so that we're clear on what this
project should accomplish.
=> Project description and spell out our goals

examples/distance_mask.py, verde/__init__.py, verde/grid_math.py
Function `distance_mask` returns a boolean array that is true when a
data point is too far from the closes data point. Uses
scipy.statial.cKDTree to calculate the distances efficiently.
=> Function to mask grid points far from data

examples/vector_trend.py, verde/__init__.py, verde/base.py, verde/tests/test_base.py, verde/tests/test_trend.py, verde/trend.py
The `VectorTrend` class fits a separate `Trend` to each component of the
data. Components can be accessed separately using
`VectorTrend.component_`. Operations of the `VectorTrend` will produce
multi-component data.
Had to generalize the `check_fit_input` function to allow for
multi-component data and weights.
=> Fit trends to vector data

verde/base.py, verde/tests/test_scipy.py, verde/tests/test_spline.py, verde/tests/test_trend.py
Calculate the R^2 score of the gridder prediction. Needed for doing
cross-validation later.
=> Add a score method to BaseGridder to calculate R2

examples/block_reduce.py, examples/chain_trend.py, examples/scipygridder.py, examples/spline.py, verde/__init__.py, verde/grid_math.py, verde/tests/test_grid_math.py
The new `BlockReduce` class implements the `filter` method and can be
used in a `Chain`.
=> Make block reduce into a filter class

examples/data/sample_california_gps.py, verde/__init__.py, verde/base.py, verde/coordinates.py
Add functions `pad_region` to add padding to a region and
`project_region` to calculate the region in projected coordinates.
Both of these will be useful for spline gridding using forces in a
regular grid.
=> Functions to pad and project a region

examples/block_reduce_weights.py, examples/chain_trend.py, examples/data/sample_rio_magnetic_anomaly.py, examples/spline.py, examples/trend.py, verde/__init__.py, verde/utils.py
Calculates the maximum absolute value of an array(s). Used to generate
the limits of the colorbar when we want it centered on zero.
Fixes #33
=> Add the maxabs function

verde/datasets/synthetic.py
It's failing because pandas is printing things differently. Should have
known better.
=> Simplify the CheckerBoard doctest

AUTHORS.md
=> Add David Hoese to AUTHORS.md

.travis.yml, examples/blockreduce.py, examples/blockreduce_weights.py, examples/blockreduce_weights_mean.py, examples/chain.py, examples/spline.py, examples/spline_weights.py, examples/vector_trend.py
There are no weights on this one so use the air temperature data from
Texas.
Renamed some of the recipes to make the order better.
Running the docs linkcheck only on the Travis Mac builds because they
sometimes fail through no fault of ours. This way, we can force merge
PRs and still have the docs deploy on master.
=> Add recipe for simple gridding with Spline

doc/api/index.rst, doc/index.rst, tutorials/overview.py, verde/__init__.py, verde/base.py, verde/chain.py
The page explains the naming conventions (fixes #2)
for coordinates, etc, and the basic gridder interface (fixes #78).
=> Overview page about conventions and usage

doc/index.rst, tutorials/overview.py, tutorials/trend_estimation.py
Explains the basic usage. Not much to it actually.
Fixes #81
=> Add a tutorial for using Trend

.appveyor.yml, .travis.yml, environment.yml, requirements.txt
Install the conda package instead of pip.
=> Use pooch from conda-forge

verde/tests/test_spline.py
**Description of proposed changes**
Give it more data and more relaxed assertions to make sure things won't
break on the whim of a floating point.
**Reminders**
=> Fix breaking test for damped spline

verde/spline.py, verde/tests/test_spline.py, verde/tests/test_vector.py, verde/vector.py
Remove the arguments for laying out forces on a regular grid. This
reduces the complexity. Instead, force coordinates can be an argument to
the class. Also, force coordinates are fixed once set so the model won't
change configuration when fitting on different data. This was a major
problem for Kfold CV and difficult to detect if you don't know what's
happening. This way, it's explicit. One can still reset the forces by
re-instantiating the interpolator or setting `force_coords` to `None`.
Affects Spline and VectorSpline2D.
**Reminders**
=> Simplify the spline arguments for force locations

doc/index.rst, tutorials/projections.py, tutorials/trend_estimation.py
Uses the bathymetry data to show how to project data and make a geographic grid from a Cartesian gridder.
Fixes #79
=> Tutorial for making geographic grids

doc/install.rst, tutorials/vectors.py, verde/tests/test_minimal.py
This test touches most of the core features of Verde and just checks the
end result. It can be a quick test to see if anything is broken, for
example when building the conda-forge package.
**Reminders**
=> Add minimal integration test

paper/paper.md
:wave: @leouieda - this is a tiny change to your JOSS paper to make it compile properly in our submission system.
=> Small LaTeX fix

paper/paper.md
=> Add acknowledgements and SOEST pub number

CITATION.rst, MAINTENANCE.md, README.rst, doc/changes.rst
Update citation to reflect the JOSS paper (accepted). Update links on
README and include a changelog.
=> Changes for 1.0.1 release and JOSS citation

AUTHORS.md, README.rst, doc/changes.rst, doc/install.rst
Created a changelog for the new 1.1.0 release with Zenodo DOI.
Updated the authors list and made it alphabetical by last name.
Updated install instructions to be clearer what numba and pykdtree do.
=> Add changelog for 1.1.0

.travis.yml
Makes it a lot easier to see which build does what in the Travis
website.
**Reminders**
=> Name the different Travis builds

examples/spline.py
Splitting only once will give results depending on the random state
chosen. Include link to the Model Selection tutorial for more
information.
**Reminders**
=> Add note to spline example about random_state

AUTHORS.md, README.rst, doc/changes.rst
Create a changelog entry and update the authors file to include
@santisoler
**Reminders**
=> Changelog entry for 1.2.0

verde/tests/test_spline.py
Warning about importing `dask.distributed` inside a test function. Move
to top of module with `try:... except:...` block.
**Reminders**
=> Fix linting issue using pylint 2.4.4

README.rst, doc/changes.rst
=> Add changelog entry for v1.3.0

AUTHORS.md
Add CONICET affiliation and specify UNSJ affiliation to IGSV.
=> Complete santisoler affiliation on AUTHORS.md

.travis.yml
Travis started warning that some options in the config were deprecated.
Update them to the new format to avoid crashing builds later on.
**Reminders**:
=> Update TravisCI configuration to new formats

README.rst
Following the instructions of "equally" important contributions .... maybe this is just a ploy to get contributors? :)
=> Minor typo fix in README

.azure-pipelines.yml, environment.yml, examples/blockkfold.py, examples/train_test_split.py, examples/trend.py, tutorials/model_selection.py, verde/base/base_classes.py, verde/mask.py, verde/tests/test_base.py, verde/tests/test_mask.py, verde/tests/test_model_selection.py
After version 19, black changed the formatting slightly in a few files.
This updates the format and sets a minimum version of black in the
development environment and the CI.
**Reminders**:
=> Require Black >=20.8b1

LICENSE.txt
Seems to be what is recommended: https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year
Related to fatiando/maintenance#9
**Reminders**:
=> Use only first year of publication in the copyright notice

doc/api/index.rst
It was missing from the list of functions.
**Reminders**:
=> Add make_xarray_grid to the API documentation

data/examples/baja_bathymetry.py
I update the GMT link.
Is that from the example gallery 15? Maybe this could clarified.
=> Update GMT link in Baja bathymetry example

MANIFEST.in
=> Include requirements.txt in MANIFEST.in

.gitignore
Ignore the .eggs directory that is created after `make install`
**Reminders**:
=> Add .eggs to .gitignore

README.rst, doc/changes.rst
=> Add changelog entry for v1.6.0

README.rst, doc/changes.rst
Minor release to include a small fix to make_xarray_grid
**Reminders**:
=> Changelog entry for v1.6.1

.github/workflows/docs.yml, .github/workflows/pypi.yml, .github/workflows/style.yml, .github/workflows/test.yml, README.rst, doc/conf.py, doc/install.rst, verde/datasets/sample_data.py
Update the default branch name is CI, documents, and dataset code.
Fixes #334
=>  Rename "master" to "main" throughout the project

README.rst, doc/index.rst
The new link to find out information about contacting us is https://www.fatiando.org/contact/
Related to fatiando/community#43
**Reminders**:
=> Update the contact link in the docs

doc/conf.py, doc/install.rst, env/requirements-docs.txt, environment.yml
Use sphinx-panels to create the tabbed version of the install commands.
Move them to the top. Remove the information about testing (we probably
don't want users running tests every time they install things).
**Reminders**:
=> Modernize the install page

doc/changes.rst, doc/versions.rst
**Description**
Minor version that introduces some deprecations and couple of new
features.
**Relevant issues/PRs**
See #341
=> Add changelog entry for v1.7.0

.github/workflows/test.yml, setup.cfg
**Description**
Remove the compatibility metadata, remove from the CI matrix, bump the
`python_requires` to 3.7+.
**Relevant issues/PRs**
Fixes #342
=> Drop support for Python 3.6

README.md, doc/changes.rst, doc/versions.rst
Add the updates to the changelog, tweaks to the README, and link to new docs version.
=> Changelog entry for v1.8.0

.github/workflows/test.yml, doc/compatibility.rst, setup.cfg
Per our policy, it's time to drop support for these.
=> Drop support for Python 3.7 and 3.8

AUTHORS.md
=> Add Gelson to the AUTHORS.md file

AUTHORS.md
Update Santiago Soler's affiliation in the `AUTHORS.md` file.
=> Update Santiago Soler's affiliation

doc/changes.rst, doc/versions.rst
Add changelog for v1.8.1. Add v1.8.1 to the list in `doc/versions.rst`.
Related to #446
=> Add changelog for v1.8.1

doc/changes.rst
Update release date for v1.8.1 in changelog.
=> Update release date for v1.8.1

doc/index.rst, doc/introduction.rst, doc/tutorial/first-grid.rst, doc/tutorial/geographic.rst
Talk about how to handle them using pyproj and the ways Verde is able to generate grids and profiles using it.
Related to #433
=> Add a tutorial about geographic coordinates

verde/spline.py
It's no longer needed since we found a workaround for the case where the distance is 0. This was been deprecated and now can be removed.
**Relevant issues/PRs:** Fixes #408
=> Remove the mindist argument from Spline

verde/utils.py
It was missing from the docstring.
**Relevant issues/PRs:** Fixes #260
=> Add a description of the `nan` arg of maxabs
