fatiando/verde

verde/__init__.py, verde/utils.py
Function `grid_coordinates` returns the 2D coordinate arrays given a region 
and a shape. Will be useful when generating grids for interpolation.
Fixes #4
=> Add function to generate coordinates for a grid

doc/api/_generate_api.rst, doc/api/index.rst, examples/data/synthetic_checkerboard.py, examples/scipygridder.py, examples/trend.py, verde/__init__.py, verde/base.py, verde/base/__init__.py, verde/datasets/synthetic.py, verde/scipy_bridge.py, verde/tests/test_base.py, verde/tests/test_scipy.py, verde/tests/test_trend.py, verde/trend.py
All fit and predict methods have been changed to use a `coordinates`
tuple instead of `easting, northing`. This will allow the classes to be
used in more generic methods that take in more than 2 coordinates, like
equivalent layers.
Move the `base` subpackage back to a module and import `BaseGridder` in
the main API.
Needed for #42
=> Use 'coordinates' instead of individual arrays

examples/chain_trend.py, examples/data/sample_rio_magnetic_anomaly.py, verde/__init__.py, verde/base.py, verde/chain.py, verde/scipy_bridge.py, verde/tests/test_chain.py, verde/tests/test_scipy.py
The `Chain` estimator takes a list of gridders. Each gridder will be fit
on the residuals of the previous one. For example, can be used to chain
trend estimation with gridding.
For a gridder to be compatible, it has to set a `residual_` attribute
in `fit` that contains `data - self.predict(coordinates)`. This is used
as input to the next gridder.
The interface is similar to the scikit-learn `Pipeline` estimator but
does not yet support everything (like accessing attributes from the
components).
Fixes #42
=> Add Chain estimator

verde/scipy_bridge.py
If coordinates are in a list, passing that along to the interpolator
causes a failure. Unpack the coordinates and pass them along in a tuple
to make sure it works.
=> Make sure ScipyGridder.predict uses tuples

verde/coordinates.py
Implement the option to generate coordinates with pixel registration.
This means that the coordinates are shifted by half a spacing and the
last element is dropped.
=> Allow grid_coordinates to use pixel registration

verde/__init__.py, verde/coordinates.py, verde/grid_math.py, verde/tests/test_grid_math.py
Replaced the numpy slicing with a `scipy.spatial.cKDTree` for labeling
the points and `pandas.DataFrame.groupby.aggregate` for the reduction.
Got a 22x speed increase.
This requires replacing `block_region` with `block_split` which does the
KDTree labeling.
=> Use KDTree and pandas groupby in block_reduce

examples/block_reduce.py, examples/chain_trend.py, examples/data/sample_california_gps.py, examples/data/sample_rio_magnetic_anomaly.py, examples/distance_mask.py, examples/scipygridder.py, examples/spline.py, examples/trend.py, examples/vector_trend.py, verde/base.py, verde/chain.py, verde/coordinates.py, verde/grid_math.py, verde/scipy_bridge.py, verde/spline.py, verde/tests/test_base.py, verde/tests/test_grid_math.py, verde/tests/test_trend.py, verde/trend.py
Some functions where using `easting, northing` as input. I changed all
of them to take in a `coordinates` tuple instead. Now everything takes
it and uses the first 2 elements. Return values are also grouped into 
coordinates tuples.
=> Standardize functions to use coordinates tuples

examples/distance_mask.py, examples/spline.py, examples/vector2d.py, verde/grid_math.py, verde/tests/test_grid_math.py
Invert the mask to make it compatible with xarray.Dataset.where without
having to negate it (~).
Allow the function to take coordinates or parameters to generate a
regular grid automatically. This way we don't need to meshgrid the grid
coordinates and just give region and spacing.
=> Refactor distance_mask to be more useful

doc/Makefile
Need to build the API before running linkcheck to make sure that
automodule was run. Otherwise the API docs don't get checked.
=> Linkcheck the API docs as well

README.rst
Remove links to API, etc, and just link to the documentation.
=> Link to latest docs in README

.appveyor.yml, .travis.yml, README.rst
AppVeyor runs builds for Python 3.5 and 3.6 on 64bit systems.
=> Enable OSX and Windows CI builds

.travis.yml, requirements.txt
Black is 3.6 only and was breaking the 3.5 build.
Remove it from `requirements.txt` and only install it if running the
code checks on 3.6 builds.
Fixes the CI failures in #92
=> Only install black on Travis for 3.6 builds

doc/install.rst, verde/blockreduce.py, verde/grid_math.py
Adds optional 'pykdtree' dependency for blockreduce and grid_math modules for better performance on the associated operations. Include notes in the docstrings for these methods and in the install instructions.
Feel free to be picky about how things are worded 😉 I get it.
Fixes #90
=> Use pykdtree if available in blockreduce and distance_mask

doc/conf.py, verde/__init__.py, verde/spline.py, verde/tests/test_spline.py, verde/tests/test_trend.py, verde/tests/test_vector.py, verde/trend.py, verde/vector.py
`Trend`, `Spline`, and `Vector2D` defined the Jacobian matrix
calculations as separate functions. Make them methods of each class
instead.
For `Spline` and `Vector2D`, the `jacobian` method is now responsible
for picking the locations of the forces. Fitting twice will remove the
existing force locations and pick new ones.
=> Make the jacobian functions into class methods

doc/api/index.rst, examples/vectorspline2d.py, verde/__init__.py, verde/spline.py, verde/tests/test_vector.py, verde/vector.py
The name Vector2D doesn't really tell anyone what it does. Also renamed
the `fudge` parameter to `mindist` which is what it really is.
=> Rename Vector2D to VectorSpline2D

verde/tests/test_vector.py, verde/vector.py
Jacobian calculation speeds are 5-10x but results is small or
non-existent speedups in the actual fitting because there the
least-squares dominates the computation time. Still, good to have the
feature.
=> Add numba version of VectorSpline2D jacobian

.travis.yml
Checking links fails too often for reasons that are not in our control.
=> Don't check doc external links on CI

doc/index.rst, tutorials/model_selection.py
Show how to use `train_test_split` and the `score` method.
Use the air temperature data because it's sparse. The bathymetry data is
too good to need much tuning.
Fixes #82
**Reminders**
=> Add tutorial for model selection

verde/__init__.py, verde/base.py, verde/blockreduce.py, verde/chain.py, verde/coordinates.py, verde/utils.py
Simplify the code by using the `n_1d_arrays` utility function.
Had to move `check_data` to `utils` to avoid a circular dependency
problem. Not a big deal since it really doesn't depend on anything in
`base`.
**Reminders**
=> Refactor block_split and move to coordinates module

CITATION.rst, MAINTENANCE.md, README.rst, doc/changes.rst, doc/citing.rst, doc/index.rst
In preparation for the 1.0.0 release, add a changelog with a minimal
entry, instructions for archiving on Zenodo, and citation information
(Zenodo for now until there is a paper).
=> Add citation info and a changelog

data/examples/checkerboard.py, verde/base.py, verde/tests/test_scipy.py
There is no reason to have one and it wasn't even implemented in
`grid_coordinates`. This only affected a single example of CheckerBoard
that didn't set `shape` or `spacing`.
**Reminders**
=> Remove default shape for BaseGridder.grid

verde/model_selection.py
scikit-learn will change the default from 3 to 5 in an upcoming release.
Set the value to 5 now to prepare and make sure that future changes
don't affect us.
**Reminders**
=> Set default n_splits=5 in scikit-learn KFold

verde/coordinates.py, verde/tests/test_blockreduce.py
The `grid_coordinates`, `scatter_points`, and `profile_coordinates` all
accept a new a `extra_coords` argument with the constant value to be
used as an extra coordinate. If given, then the output will have an
extra coordinate array of the same shape as the rest and with that
single value. If a list is given, multiple extra coordinate arrays will
be returned.
This can be used to specify constant coordinates to a grid generator,
like height or time, to generate a 2D grid/scatter/profile from data
that requires 3+ coordinates.
A step towards #138
**Reminders**
=> Add extra_coords option to coordinate generators

verde/spline.py, verde/tests/test_spline.py, verde/tests/test_vector.py, verde/trend.py, verde/vector.py
All gridders create a Jacobian matrix to make predictions (using a dot product with the estimated parameters). This is very inefficient with regards to memory. Generating large*ish* grids requires a huge amount of RAM.
Replace these with a for loop summation. Accelerate them with numba to achieve the same performance. The pure Python version is slower than the dot product but at least it won't blow up memory.
**Reminders**
=> Don't use the Jacobian for prediction

examples/scipygridder.py, examples/spline.py, examples/spline_weights.py, examples/vector_trend.py, tutorials/chain.py, tutorials/model_selection.py, tutorials/projections.py, tutorials/vectors.py, tutorials/weights.py
It automatically adjusts the coordinates to match the center of each
pixel. Using matplotlib's pcolormesh would result in pixels being off by
0.5*spacing unless we have pixel registered grids (which we don't).
Fixes #147
**Reminders**
=> Use the xarray pcolormesh to plot grids

.appveyor.yml, .travis.yml, setup.py, verde/utils.py
Add a Python 3.7 build on Travis and the 3.7 language marker to
`setup.py`.
=> Test and support Python 3.7

verde/utils.py
`verde.maxabs` now uses the `nan*` version of numpy functions by default
to handle arrays with NaNs (like masked grids). This can be turned off
with an argument in case the not `nan` behavior is desired.
**Reminders**
=> Allow maxabs to handle inputs with NaNs

tutorials/model_selection.py
The previous version used the `train_test_split`, which was highly
sensitive to the random number seed. Update the tutorial to show this
effect and use `cross_val_score` instead for a better metric. Use only a
single `Spline` instead of the `Chain` because it's not needed for this
dataset.
**Reminders**
=> Use cross_val_score in model selection tutorial

verde/tests/test_trend.py, verde/trend.py
There was no real reason to not allow them in the past. A zero degree
polynomial is a mean. This can be useful to test if a simple static
shift in the data is enough of a trend.
**Reminders**
=> Allow zero degree polynomials in Trend (a mean)

verde/model_selection.py
The scheduler looses some processes for some reason. Use threads in the
example to fix this.
**Reminders**
=> Dask tests fail on AppVeyor if using processes

.pylintrc, .travis.yml, doc/conf.py, environment.yml, requirements-dev.txt
A pylint update introduced new failures, all false positives regarding
numpy. I disabled them and fixed the pylint version to avoid this
happening without our control.
While I was at it, I removed some unused dependencies (jupyter and
nbsphinx) and removed the restriction on matplotlib (no longer applies).
**Reminders**
=> Fix lint errors and update dev requirements

AUTHORS.md, LICENSE.txt, README.rst, doc/conf.py, setup.py
Replaces my name with "The Verde Developers" in authorship claims and
copyright notices. Include a definition of what that term means in the
`AUTHORS.md` file and include a reference to it in the README and doc
page.
Left my name and email as maintainer on the `setup.py` because we don't
have a project email yet.
Hopefully this will make things a bit more transparent and equal.
=> Assign authorship to "The Verde Developers"

.travis.yml, doc/install.rst, setup.py
Remove the CI checks, update the install instructions, and bump the
required version in `setup.py`.
Fixes #175
**Reminders**
=> Drop support for Python 3.5

verde/coordinates.py
Fix a bug in `grid_coordinates` when passing `pixel_register=True` and
`shape` instead of `spacing`. The returned coordinates had 1 too few
elements in each dimension (and the wrong values). This is because we
generate grid-line registered points first and then shift them to the
center of the pixels and drop the last point. This only works when
specifying `spacing` because it will generate the right amount of
points. When `shape` is given, we need to first convert it to
"grid-line" shape (with 1 extra point per dimension) before generating
coordinates.
**Reminders**
=> Fix wrong coordinates for pixel-register and shape

verde/blockreduce.py, verde/coordinates.py, verde/tests/test_blockreduce.py
`block_split` and `BlockReduce`/`BlockMean` (which relied on it) only
allowed defining the block size by `spacing`. Now they an take a `shape`
as well. Useful when the size of the block is less meaningful than the
number of blocks (like in spatial cross-validation splitting).
**Reminders**
=> Allow block_split and BlockReduce to take a shape

doc/api/index.rst, examples/spline_cv.py, tutorials/overview.py, verde/__init__.py, verde/model_selection.py, verde/spline.py, verde/tests/test_spline.py, verde/tests/utils.py
The `SplineCV` class perfoms grid search cross-validation to auto-tune a `Spline`.
It uses `cross_val_score` to cross-validate and can be configured to run in parallel
with a `dask.distributed.Client` and take different scikit-learn splitters besides
`KFold`. Tested on the checkerboard function and add a gallery example using the
Texas temperature data.
**Reminders**
=> Add SplineCV: a cross-validated Spline

doc/index.rst, tutorials/model_evaluation.py, tutorials/model_selection.py
The previous model selection tutorial covered both scoring and automatic
tuning. Separate into two tutorials "Evaluating Performance" and "Model
Selection" so they are both shorter.
Include a section in "Model Selection" about the new `SplineCV` class
from #185.
**Reminders**
=> Split model selection and evaluation tutorials 

verde/model_selection.py, verde/spline.py, verde/utils.py
This was in verde/model_selection for some reason. It should be in utils
instead and not public.
**Reminders**
=> Move the DummyClient to the verde/utils module

verde/spline.py, verde/tests/test_spline.py
Previously, the `Spline` set the force coordinates from the data
coordinates only the first time `.fit` was called. This means that when
fitting on different data, the spline would still use the old force
coordinates. Now, the spline will use the coordinates of the current
data passed to `fit`. This only affects cases where `force_coords=None`.
It's a slight change and only affects some of the scores for
cross-validation.
**Reminders**
=> Bug fix: Reset force coords when refitting splines

verde/base/base_classes.py, verde/datasets/synthetic.py, verde/tests/test_spline.py
Some tests rely on checking if the code gives a warning. The test was
checking if the number of warnings is 1 and comparing the error message.
This breaks if any of our dependencies introduce warnings.
Fix by checking if >=1 warning and if any have the right message.
**Reminders**
=> Fix breaking Spline test due to extra warnings

doc/api/index.rst, verde/__init__.py, verde/coordinates.py, verde/tests/test_coordinates.py
Add `latlon_continuity()` function that moves a set of longitudinal coordinates either
to the `[0, 360)` or `[-180, 180)` degrees intervals, depending which one is more suited for
that particular set of coordinates.
It also allow to modify an extra set of coordinates based on the decision made on the
first set.
Modify the `inside()` function to enhance how the inside points are selected, even if
their longitudinal coordinates are not defined on the same degree interval. 
Fixes #171 
**Reminders**
=> Add enhanced support for geographic coordinates

verde/blockreduce.py, verde/tests/test_blockreduce.py
Include additional coordinates when reducing data and observation points.
Fixes #195
**Reminders**
=> Add support for n-dimensional coordinates on BlockReduce

.azure-pipelines.yml, .travis.yml, verde/__init__.py, verde/datasets/sample_data.py, verde/tests/test_utils.py, verde/tests/utils.py, verde/utils.py
Pylint 2.4.2 generates some new error reports, mostly due to imports not
being at the top. Fix these by moving most imports to top.
Update CI scripts to 1.2.0 to fix failing TravisCI builds.
Take control of the conda path on Mac Azure builds to avoid conda
errors.
**Reminders**
=> Update CI scripts and fix linting errors

README.rst, doc/conf.py
Use out new domain forward contact.fatiando.org to send people towards
Slack. In the docs, this can also be stable and we can update (even for
older pages) as needed.
**Reminders**
=> Update contact information to point to Slack

verde/base/base_classes.py, verde/chain.py, verde/scipygridder.py, verde/spline.py, verde/trend.py, verde/vector.py
The attributes argument for the sklearn.utils.validation.check_is_fitted
function is going to be deprecated. Remove the attributes passed to the
check_is_fitted function used on the predict method of every predictor
from Verde. Modify the example on verde.base.BaseGridder to show how the
check_is_fitted function must be used when subclassing the BaseGridder.
Fixes #216
**Reminders**
=> Remove attributes argument from check_is_fitted

verde/base/base_classes.py, verde/chain.py, verde/scipygridder.py, verde/spline.py, verde/trend.py, verde/vector.py
Rollback the changes in #217 because scikit-learn reverted the deprecation of 
`attributes` in `check_is_fitted`. See scikit-learn/scikit-learn#15947
=> Revert the use of attributes in check_is_fitted

verde/spline.py
SplineCV was keeping the best Spline instance in `SplineCV._best` which
goes against the scikit-learn standard of storing estimated parameters
in variables ending in `_`. Change that to `SplineCV.spline_` and add it
to the class attribute list.
**Reminders**
=> Expose the optimal spline in SplineCV

.azure-pipelines.yml, .travis.yml, data/examples/README.txt, doc/api/index.rst, requirements.txt, setup.py, verde/datasets/__init__.py, verde/datasets/sample_data.py, verde/tests/test_datasets.py
With Pooch 0.7.0, the recommended way of loading the registry file is
with `pkg_resources` (see fatiando/pooch#120). It's also better to use
the default cache location so users can more easily clean up unused
files. Because this is system specific, add the `verde.datasets.locate`
function to return the cache folder location.
**Reminders**
=> Use pooch.os_cache and pkg_resources in datasets

AUTHORS.md
The authorship guidelines introduced in fatiando/contributing#13 specify that authors on Zenodo archives will be taken from the `AUTHORS.md` file and need to have full names, affiliation, and ORCIDs (optionally) included in that file. 
**Reminders**
=> Add affiliations and ORCIDs to AUTHORS file

verde/utils.py
Previously would fail because we rely on getting the data variable names
from the Dataset. Need to check if it's a Dataset (has the `data_vars`
attribute) and set the data column name to differently if it's not.
The data column name will be `DataArray.name` or "scalars" (if it's None).
Fixes #225
**Reminders**:
=> Allow grid_to_table to take DataArrays

doc/api/index.rst, verde/__init__.py, verde/coordinates.py, verde/tests/test_coordinates.py
The `rolling_window` function returns the indices of points falling on
rolling/moving windows. It works for irregularly sampled data and is a
nice complement to `xarray.DataArray.rolling`  (which only works on
grids). Uses a KDTree to select points but is not compatible with
pykdtree (it's missing the method we need).
**Reminders**:
=> Add function for rolling windows on irregular data

doc/api/index.rst, verde/__init__.py, verde/base/utils.py, verde/coordinates.py, verde/tests/test_base.py
For selecting data in windows of various size around a center point.
Sizes do not have to be increasing necessarily. Returns only the indices
of points falling inside each window.
Follow-up to  #236 and also very useful in things like Euler deconvolution. Will need to be rebased once  #236 is merged because it introduces a new utility function to get rid of repeated code between the pull requests (checking if the coordinates are all of the same shape).
**Reminders**:
=> Add function to split data on an expanding window

verde/coordinates.py
The `rolling_window` and `expanding_window` functions fail if given more 2 coordinates.
If we had full support for N-D coordinates, they could be N-D windowing functions
but until that time, they will have to be 2D (horizontal) only functions. Add test cases using
`extra_coords` in `grid_coordinates` to generate a third coordinate.
Fixes #242 
**Reminders**:
=> Fix bug for 3+ coordinates in windowing functions

verde/base/base_classes.py, verde/tests/test_base.py, verde/utils.py
Make docstrings of `BaseGridder` more general, without specifying
a coordinate system. Add `dims` as a class variable that will be used by
default on `grid`, `scatter` and `profile` methods.
Fixes #239
**Reminders**:
=> Generalize BaseGridder docstrings

doc/api/index.rst, examples/convex_hull_mask.py, examples/spline_weights.py, examples/vector_uncoupled.py, tutorials/weights.py, verde/__init__.py, verde/mask.py, verde/tests/test_mask.py
Use scipy's Delaunay triangulation to determine points that are outside
the convex hull of the data points. Useful to mask out wildly
extrapolated points from grids. It's easier to use than `distance_mask`
because it doesn't require distance calculations (and the associated
projections). Use the new function in some examples and tutorials.
Fixes #126
**Reminders**:
=> Add a convex hull masking function

doc/api/index.rst, examples/project_grid.py, verde/__init__.py, verde/coordinates.py, verde/projections.py, verde/tests/test_projections.py
The `project_grid` function transforms a grid to the given projection. It re-samples the data using `ScipyGridder` (by default) and runs a blocked mean (optional) to avoid aliasing when the points aren't evenly distributed in the projected coordinates (like in polar projections). Applies a `convexhul_mask` to the grid always to avoid extrapolation to points that had no original data (this is done by scipy for linear and cubic interpolation already). 
The function only works for `xarray.DataArray`s (not `Dataset`) because I couldn't find an easy way to guarantee that a variables have the same dimensions. We can add that option later on if needed. It wouldn't break the API so we can use this as a minimum viable product for now.
Move the new function and `project_region` to the new module …
=> Add function to project 2D gridded data

README.rst, doc/changes.rst
New minor release with new features and bug fixes. No breaking changes
or deprecations.
**Reminders**:
=> Changelog entry for v1.4.0

.travis.yml
The docs and configuration validation tool had recommended using
`cleanup: false` instead of `skip_cleanup: true` when deploying. Turns
out Travis decided to ignore the new parameter and our Github Pages
deploy was broken since the docs were deleted before we could deploy.
Revert back to the old argument until Travis really removes it.
**Reminders**:
=> Fix broken TravisCI deploy

verde/base/least_squares.py, verde/tests/test_base.py
Add new `copy_jacobian` optional argument to `least_squares` to avoid scaling Jacobian matrix inplace. Add warning on its docstring warning about memory consumption when `copy_jacobian` is True. Add test function for this new feature.
Fixes #252 
**Reminders**:
=> Add optional argument to least_squares to copy Jacobian matrix

examples/train_test_split.py, verde/model_selection.py
Add option `blocked=False` to `verde.train_test_split` that uses `BlockShuffleSplit` if `True` instead of the scikit-learn `ShuffleSplit`. Also add a gallery example comparing the two options. 
**Reminders**:
=> Add a blocked option for train_test_split

verde/base/base_classes.py, verde/tests/test_base.py
Update tests functions to the new default representation of Scikit Learn
gridders. The expected outputs when printing Verde gridders has been
updated following this new default behaviour. After 0.23, Scikit Learn
only shows those parameters whose default value has been changed when
giving a string representation of the gridder. See
scikit-learn/scikit-learn#17061 and its changelog for more information.
Fix #266
**Reminders**:
=> Update tests to new Scikit Learn gridders representation

environment.yml, requirements-dev.txt
For some reason, the coast lines features are plotting on the entire
figure instead of only the land or ocean. Might be an error on our side.
For now, pin cartopy on CI to fix our docs.
**Reminders**:
=> Pin Cartopy to 0.17.* until we sort out problems

README.rst, doc/changes.rst
Includes the new cross-validators and fixes to our base classes to
accommodate Harmonica.
**Reminders**:
=> Changelog entry for v1.5.0

verde/base/base_classes.py, verde/base/utils.py, verde/model_selection.py, verde/tests/test_model_selection.py
Currently, `cross_val_score` only uses the estimator's `.score` method (which is R² for all our gridders). But sometimes we want to use a different metric, like MSE or MAE. These changes allow passing in any scikit-learn compatible scorer through a new `scoring` parameter. This can be a string or callable, like in scikit-learn's `cross_val_score`. Needed to delegate score computation to a separate function in `verde.base.utils` to reuse in `cross_val_score` and a dummy class to be able to use the scikit-learn scorers correctly. 
**Reminders**:
=> Allow specifing the scoring function in cross_val_score

verde/base/base_classes.py, verde/base/utils.py, verde/tests/test_base.py, verde/tests/test_utils.py, verde/utils.py
Refactor `get_data_names` as a method of `BaseGridder`: simplify
`get_data_names` logic, make `get_data_names` to use `check_data_names` to
convert single string to a tuple and check that `data_names` has the same
number of elements as data. Add `data_names_defaults` as a class attribute of
`BaseGridder`. Move `check_extra_coords_names` to `verde/base/utils.py` along
with the other check functions. Make `check_data_names` to raise error if
`data_names` is `None`. But `BaseGridder.get_data_names` will return default
values if `data_names` is `None`. Rename test functions for `make_xarray_grid`.
**Reminders**:
=> Refactor get_data_names and check functions

verde/distances.py, verde/model_selection.py
This pull-request Fixes #287.  It cherry-picks jcrawfords original work on this (seen in unmerged/closed pr #288) and adds the change requested by santisoler (in pr #288).
**Reminders**:
Let me know if this change could be accepted (or rejected) or needs some additional changes to be approved and merged.
Thank you,
DC Slagel
=> Fix typos in docstrings

verde/base/base_classes.py, verde/base/utils.py, verde/tests/test_coordinates.py
Fix a common typo on Verde: replace "coordiantes" for "coordinates".
**Reminders**:
=> Fix typo on "coordinates"

setup.py
On `setup.py`, build the `INSTALL_REQUIRES` variable by reading the `requirements.txt` file.
**Reminders**:
=> Get INSTALL_REQUIRES from requirements.txt

environment.yml, requirements.txt
Dask 2021.03.0 was causing the tests to fail under Python 3.8 on any OS.
The problem seems to be originated by `dask.distributed`.
By excluding this version, we avoid the problem in the future.
Fixes #310 
**Reminders**:
=> Exclude Dask 2021.03.0 as a dependency

.github/workflows/pypi.yml
For test releases to TestPyPI we have to edit the setuptools_scm
configuration to produce valid version numbers. But it turns out that
this breaks the number for actual releases. To fix it, only edit the
configuration on non-release builds.
This change should be ported to Harmonica as well.
**Reminders**:
=> Fix wrong version numbers for PyPI releases

verde/tests/test_utils.py, verde/utils.py
Allow `make_xarray_grid` to get `data` as None, generating a `xr.Dataset`
without any `data_vars` array, containing only the coordinates.
Might be useful in some cases to define an `xr.Dataset` with coordinates only
and add the `data_vars` afterwards.
**Reminders**:
=> Allow make_xarray_grid to get data as None

.github/workflows/test.yml, setup.py
Add Python 3.9 to the CI tests.
Related to fatiando/maintenance#14
**Reminders**:
=> Extend support for Python 3.9

examples/vector_uncoupled.py, verde/tests/test_base.py, verde/tests/test_spline.py
Explicitly pass default arguments with their corresponding keywords on tests
and examples. Particularly for grid_coordinates and BaseGridder.grid calls.
It's better if we instruct people to use keywords of default arguments instead
of passing them by order, this way can add or change the order of default
arguments without breaking backward compatibility.
**Reminders**:
=> Use keywords for default arguments in tests and examples

verde/utils.py
Change the order of the dimensions of `DataArrays` in the examples of
`make_xarray_grid`, since `xarray v0.19.0` prints them in a different order.
Tell `pytest` to ignore the outputs of the `print` statements in the
`make_xarray_grid` examples while running doctests.
**Reminders**:
=> Change order of dims in example of make_xarray_grid

env/requirements-build.txt
The [tomli](https://github.com/hukkin/tomli) package dropped 3.6 in it's 2.0.0 release and our dependencies didn't pin their upper versions. Restrict this to >2.0 for now until we drop Python 3.6. It's not a run-time dependency, only for building and testing.
**Reminders**:
=> Fix broken Python 3.6 builds

verde/base/base_classes.py
Issue a warning in the code and docstring that the default scoring
method used in the `score` method will change from R² to negative root
mean squared error.
Fixes #340
**Reminders**:
=> Warn that the default score will change in 2.0

data/examples/checkerboard.py, doc/api/index.rst, examples/project_grid.py, tutorials/overview.py, verde/__init__.py, verde/base/base_classes.py, verde/datasets/synthetic.py, verde/synthetic.py, verde/tests/test_chain.py, verde/tests/test_scipy.py, verde/tests/test_spline.py, verde/tests/test_vector.py
Create a new module `verde.synthetic` to house the `CheckerBoard` class. The module is imported in `__init__.py` and a version of `CheckerBoard` is maintained in `verde.datasets` that issues a warning when used. 
Fixes #349 
**Reminders**:
=> Move the CheckerBoard class to verde.synthetic

README.rst, doc/api/index.rst, doc/index.rst, doc/versions.rst, verde/synthetic.py
Use sphinx-panels to make the 4 box callouts to sections of the docs.
Stop reusing the README and instead have a single paragraph explaining
what Verde is. Reuse this paragraph in the README since that one needed
some updating as well. Move the links to other versions of the docs into
it's own page. Rename the API reference to something more informative.
Remove the deprecated `test` function from the API reference.
**Reminders**:
=> Modernize the front page of the docs

doc/gallery_src/blockreduce_weights_mean.py, doc/gallery_src/spline_weights.py, doc/gallery_src/vector_trend.py, doc/tutorials_src/vectors.py, doc/tutorials_src/weights.py, verde/spline.py, verde/tests/test_blockreduce.py, verde/tests/test_minimal.py, verde/tests/test_projections.py, verde/tests/test_utils.py, verde/trend.py, verde/vector.py
**Description**
Black is now out of beta and has introduced a small change in the
syntax, removing white space around `**` operators. They also now
promise to only update syntax like this at most once a year. Seems
reasonable and not a lot of work to keep up to date without pinning
black.
**Relevant issues/PRs**
Reason why #346 is broken. After merging, should work fine.
=> Update the new 2022 black syntax

verde/coordinates.py, verde/trend.py
**Description**
Numpy dtypes like `np.bool` and `np.int` have been deprecated since Numpy v1.2.0 in favor of using
builtin `bool` or `int`, or even `np.int64` and `np.int32` which explicitly
sets their precision.
See https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
for a list of deprecated data types.
=> Replace deprecated numpy dtypes np.bool and np.int

verde/spline.py
The numpy-based engine will be removed in favour of the numba-based one
which is faster and more memory efficient. This will make numba a
required dependency.
**Relevant issues/PRs:** Fixes #370
=> Deprecate the `engine` argument of Spline/SplineCV

doc/api/index.rst, doc/gallery_src/cubic_gridder.py, verde/__init__.py, verde/scipygridder.py, verde/tests/test_scipy.py
This class replaces `ScipyGridder(method="cubic")` to provide a nicer
looking interface. It'll also allow us to deprecate `ScipyGridder`
and add an `extrapolate` keyword argument in the future to replace the
NaNs outside of the convex hull with nearest neighbor values.
=> Add a Cubic gridder class based on SciPy

verde/spline.py, verde/tests/test_spline.py
I've added `scoring` as an additional parameter in `SplineCV` to control the scoring metric used during cross-validation. I've also added a simple test to `test_spline.py`, which checks that results from `SplineCV` using the new scoring parameter match those from standard `Spline` combined with `cross_val_score`. I'm not sure I've put this test in the right place - please let me know if it should be elsewhere.
(Hopefully) fixes #379 (see also the discussion [here](https://github.com/orgs/fatiando/discussions/61)).
=> Add `scoring` parameter for SplineCV

doc/conf.py
When enabling PyGMT image scraping, I forgot to add in the matplotlib scraper explicitly.
=> Add missing matplotlib scraper for sphinx-gallery

doc/gallery_src/cubic_gridder.py, verde/scipygridder.py
Rescaling can have problems and generate unintended outputs. Since Scipy defaults to not rescaling, let's do that here as well.
=> Default to not rescale coordinates in Linear/Cubic

verde/projections.py, verde/tests/test_projections.py
Now that ScipyGridder is deprecated, use the new classes in this function instead. Doesn't affect the overall interface.
Fixes #363
=> Use Linear/Cubic/KNeighbors in project_grid

verde/base/base_classes.py, verde/tests/test_base.py
These arguments of the `grid` method were to be removed in favour of generating coordinates in `grid_coordinates` but after experiments this new interface was found to be too verbose and a step backwards from the previous one.
Fixes #392
=> Undo deprecation of region/spacing/shape in grid

verde/base/base_classes.py
noticed a typo in the docstrings. 'No very useful' -> 'Not very useful'
=> Fix typo in the BaseGridder.fit docstring

verde/utils.py
Make it clearer that the `verde.make_xarray_grid` function expects 2d arrays as
inputs and it does not perform any interpolation or gridding. Add an admonition
pointing users to interpolator classes.
These changes were triggered by the https://github.com/orgs/fatiando/discussions/84 discussion in our forum.
=> Improve docstring of `make_xarray_grid`

doc/api/index.rst
The functions and classes that will be removed in Verde 2.0.0 are grouped together at the end of the API docs to help discourage people from relying on them.
=> Move deprecated APIs to their own docs section

verde/__init__.py, verde/base/base_classes.py, verde/coordinates.py, verde/datasets/sample_data.py, verde/datasets/synthetic.py, verde/model_selection.py, verde/neighbors.py, verde/spline.py
Flake8 was complaining about not setting the stacklevel in calls to `warnings.warn`. Fix this linting issue since it's a good thing to set.
=> More informative warning by setting stacklevel=2

verde/coordinates.py, verde/tests/test_coordinates.py
This was a bug caused by the rounding when calculating the number of nodes in `spacing_to_size`. For the case where the spacing is larger than twice the interval, the size calculating rounded to zero which meant that we were getting a single value for the number of nodes. This is clearly wrong since our behavior is to change the spacing or the region to make sure we always produce at least 2 nodes in the interval.
Fixes #404
=> Fix behavior if spacing >= 2 * interval

.github/workflows/test.yml
Let the CI job fail if the codecov upload fails. Otherwise it could stop and we wouldn't know.
=> Fail CI if codecov upload fails

verde/vector.py
The numpy versions of these functions will be removed in Verde 2.0.0 in favour of the better numba-based versions.
=> Deprecate the engine parameter in VectorSpline2D

doc/gallery_src/spline.py, doc/gallery_src/spline_cv.py, doc/gallery_src/vector_uncoupled.py, doc/tutorials_src/model_selection.py, verde/spline.py, verde/tests/test_spline.py
If distance is small change the Green's function to `x(log(x**x)-1)` which evaluates to the correct limit of 0. Deprecate the `mindist` parameter in `Spline` and `SplineCV` since it's no longer needed. Remove use of this parameter from the documentation and present `damping` as the only configurable parameter for the splines.
=> Use a better Spline Green's function for small distances

pyproject.toml
Since `setup.py` was removed from Verde, the comment in `pyproject.toml` should be updated and remove "setup.py" from it.
=> Remove mention of "setup.py" from pyproject.toml

.github/dependabot.yml
The bot can make PRs when new versions of the Actions we use are released. Best way to keep them updated.
=> Add Dependabot config to update GitHub Actions

.github/workflows/docs.yml
This should fix the deployment of the docs.
=> Bump actions/download-artifact to v4 in docs

.github/workflows/pypi.yml
This fixes the failed upload to TestPyPI using Trusted Publishers.
=> Bump pypa/gh-action-pypi-publish to v1.8.12

verde/utils.py
Add lines to search for extra coordinates and append the information into the list of coordinates and coordinates_name
Fixes #403 
=> Fix dropping non-dimensional coordinates in grid_to_table

.github/workflows/docs.yml, .github/workflows/pypi.yml, .github/workflows/style.yml, .github/workflows/test.yml, environment.yml, setup.cfg
Use Python 3.12 as latest version in CI and environment.yml. Update categories in `setup.cfg`.
=> Extend support for Python 3.12

.github/workflows/docs.yml, environment.yml
The `build` package in `conda-forge` is outdated, `python-build` should be used instead. Add step in `test.yml` GitHub Action to replace `build` for `python-build` in the collected dependencies that will be installed with conda.
=> Replace `build` for `python-build` in environment.yml

verde/coordinates.py
Remove lines that used to lower the Numpy's precision on docstring examples. Doctests started to fail on Numpy v2.0.0 due to these lines.
=> Don't configure Numpy precision in doctests

verde/coordinates.py
Remove lines that used to raise the Numpy's precision on docstring examples. Doctests started to fail on Numpy v2.0.0 due to these lines.
Account for missed lines in #462
=> Don't raise Numpy's precision in doctests

.github/workflows/test.yml
Replace `build` for `python-build` in the `test.yml` workflow before installing the required packages.
Apply changes missed in #460
=> Use `python-build` in `test.yml` workflow

doc/tutorials_src/model_evaluation.py, doc/tutorials_src/model_selection.py, verde/coordinates.py, verde/model_selection.py, verde/spline.py, verde/utils.py
When reading through the docs I noticed a few small errors which I've  fix here. 
1) The sphinx cross-referencing to the dask delayed function (:func:`dask.delayed`) was not properly working throughout the docs. It looks like the proper reference for it is :func:`dask.delayed.delayed`.  I've updated all these cross-references.
2) In the typehints of the docstrings the use of an oxford comma seems to result in "or" being treated as an object instead of text; see the docstrings for the scoring parameter of [SplineCV](https://www.fatiando.org/verde/dev/api/generated/verde.SplineCV.html#verde.SplineCV) for an example.  I've removed the oxford comma for a few docstrings that had them. 
I built the docs locally and the changes seem to have worked.
=> Minor fixes to docs

.github/workflows/docs.yml
Create a "dev2" folder in the gh-pages branch for the 2.0-dev branch docs. This is useful since a lot of the work on 2.0 is a complete rewrite of the docs. Need to undo this before the 2.0 release.
=> Deploy docs for the 2.0-dev branch

doc/api/index.rst, verde/__init__.py, verde/scipygridder.py, verde/tests/test_chain.py, verde/tests/test_scipy.py
This class was deprecated and replaced by Linear, Cubic, and KNearest. Remove it from the codebase along with tests and docs.
**Relevant issues/PRs:** Fixes #377
=> Remove the ScipyGridder class

verde/model_selection.py, verde/spline.py, verde/tests/test_model_selection.py, verde/tests/test_spline.py, verde/utils.py
The client argument was deprecated in favor of the delayed interface of Dask. Remove it now from the few places that it was present.
**Relevant issues/PRs:** Closes #351
=> Remove the client argument from dask-enabled code

doc/install.rst, environment.yml, setup.cfg, verde/spline.py, verde/tests/test_spline.py, verde/tests/test_utils.py, verde/tests/test_vector.py, verde/utils.py, verde/vector.py
Numba will be required from 2.0 and so the slower numpy engine isn't needed anymore. Remove the engine argument from Spline and VectorSpline2D. Remove utils functions that are no longer used. Remove the numpy-based code from both classes.
**Relevant issues/PRs:** Closes #369
=> Remove the engine argument and numpy backend

verde/spline.py, verde/tests/test_spline.py, verde/vector.py
We're using numba's parallel execution in Spline and VectorSpline2D and they're great. But turns out using that in a `ThreadPoolExecutor` (which dask uses) when numba was installed with pip causes a crash. This is because the threading backend that numba uses from pip on Mac (called "workqueue") is not thread-safe and aborts the process when it's inside another threading layer. There are workarounds in the numbagg package but they're complicated and involve caching of jit-compiled functions. We'll use a simpler solution and allow users to turn off parallelism and add a note in the docs about avoiding it when it would cause a crash.
**Relevant issues/PRs:** See discussion in https://github.com/numba/numba/issues/9288 and https://github.com/numbagg/numbagg/pull/201
=> Add an option to disable parallelism in splines

.github/workflows/docs.yml, .github/workflows/test.yml, doc/install.rst, environment.yml, setup.cfg, verde/coordinates.py, verde/distances.py, verde/mask.py, verde/neighbors.py, verde/tests/test_utils.py, verde/utils.py
The newer KDTree in Scipy is already very fast and the difference isn't as big. It's not worth the effort of maintaining an optional dependency in terms of CI runs and code complexity. Since Verde doesn't have optional dependencies now, we don't need the extra run of the CI.
=> Remove pykdtree as an optional dependency

verde/base/base_classes.py
On second thought, that's not really necessary as the R² is good in most cases. If RMSE is wanted, we can still do it on the SplineCV and cross_val_score.
**Relevant issues/PRs:** Fixes #322
=> Undo changing the default scoring to negative RMSE

.github/workflows/docs.yml, .github/workflows/pypi.yml, .github/workflows/test.yml
For security, it's better to pin versions of third-party Actions to commit hashes. This is because the tags used for versions can be changed to point to a different (possibly malicious) commit while the hash can't. Dependabot can still update using the hashes so it's not a huge issue.
=> Pin third-party Actions using commit hashes

doc/api/index.rst, src/verde/__init__.py, src/verde/coordinates.py, test/test_coordinates.py
This function was moved to Bordado. Remove it from the codebase and use the Bordado version. Also removed the `spacing_to_size` function which was only used by `line_coordinates`. Remove the associated tests and the API entry.
**Relevant issues/PRs:** #497
=> Remove line_coordinates which has moved to Bordado

doc/_templates/autosummary/class.rst, doc/conf.py
The combination of autosummary and numpydoc was causing warnings about missing stub files because numpydoc was building a toctree for methods but the pages didn't exist (they are all in the main page). Disable this option and remove the attribute autogenerated pages since we already describe important attributes in the docstring.
=> Fix sphinx warnings about autosummary stub files
